#config greeting
security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints
    
# <----This section is where we change debug mode
logging: 
  level:
    io:
      pivotal: INFO
      